# Differentialligninger

In [11]:
import numpy as np
from scipy.integrate import odeint
#løsning af differentialligning
y_first_t=1
ts=[0,3]
#evt.
ts1 = np.arange(4)
#odeint(fkt,startværdi for afhængig variabel, interval for uafhængig variabel(liste[]))
dydt = odeint(lambda y,t: 0.9*y**2*np.cos(t),y_first_t,ts1)
dydt

array([[1.        ],
       [4.1207187 ],
       [5.50562872],
       [1.14548591]])

In [12]:
np.arange(4)

array([0, 1, 2, 3])

In [14]:
dydts=dydt[:,0]
dydts

array([1.        , 4.1207187 , 5.50562872, 1.14548591])